# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  banjackalcom:
    image: banjackalcom
    build:
      context: .
      dockerfile: site/Dockerfile
    ports:
      - 9000:80
